import { ProductionPlan } from '../planning/productionplan';
import { Product } from '../products/product';

export interface HeijunkaBox {
  idBox?: string; // Optional ID, assuming it's auto-generated by the backend

  title: string;
  productionPlan: ProductionPlan; // The production plan associated with the Heijunka box
  products: Product[]; // List of products associated with the Heijunka box
  timestamp: Date;
  notes?: string;
  image?: string;
  archived?: boolean;
  schedule: {
    Day: string;
    Product: string;
    ProductionQuantity: number;
    TimeSlot: string;
  }[]; // Array of schedule entries with details for each day, product, quantity, and time slot
}
